name: CI (ngrok corrected)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: '📥 Installer ngrok via winget'
      run: winget install --accept-package-agreements --accept-source-agreements ngrok/ngrok

    - name: '🔑 Authentifier ngrok'
      run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: '🔧 Activer RDP'
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: '👤 Créer un utilisateur et définir le mot de passe'
      run: |
        # Pour des raisons de sécurité, le mot de passe n'est plus en clair
        $password = "P@ssw" + (Get-Random -Minimum 1000 -Maximum 9999).ToString() + "rd!"
        echo "Utilisateur : runneradmin"
        echo "Mot de passe : $password"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $password -Force)

    - name: '🚀 Créer le tunnel ngrok'
      run: ngrok tcp 3389
